# Generated by Django 4.0.3 on 2022-03-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_locations_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
